spring:
  datasource:
    url: jdbc:mysql://localhost:3309/test
    username: root
    password: dev
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.hbm2ddl.auto: update
  redis:
    host: localhost
    port: 6379
    password:

carItemMapping:
  defaultCarItemMapping:
    jack: 千斤顶
    tool: 工具
    wheel: 备胎
    triangularWarningSign: 三角警示牌
    firstAidKit: 急救包
    extinguisher: 灭火器
    engineOil: 发动机油油位/泄露
    coolant: 防冻液液位/泄露
    brakeFluid: 制动液液位/泄露
    powerSteering: 转向助力泵油油位/泄露
    windscreenWasherFluid: 玻璃清洗液液位/泄露
    polyVBelt: 发动机皮带状况
    vehicleOnOutside: 车辆外部状况
    windshield: 挡风玻璃状况
    wiperBlades: 雨刮胶条状况
    tires: 轮胎状况与胎面花纹深度
    brakeSystem: 制动系统状况/漏油
    powertrainDrivetrain: 动力系统/动力传动系统状况
    exhaustSystem: 排气系统状况
    fuelSystem: 燃油系统状况
    rubberSealsJoints: 橡胶密封件和连接件状况
    bodyPanelsDamage: 车身底板状况/损坏
    horn: 喇叭
    lightsInstruments: 灯光和仪表系统
    warningFunctionIndicatorLamps: 仪表盘内警告与功能指示灯
    windscreenWiperWasher: 雨刮器与清洗系统状况
    airCondition: 空调系统
    audioEntertainment: 音响/娱乐系统
    lighter: 点烟器
    mirror: 内/外后视镜
    windowSunRoof: 电动车窗/天窗
    seatsSeatCovers: 座椅与座椅套
    safetyBeltsBuckle: 安全带及锁扣

  smartCarItemMapping:
    jack: 千斤顶
    tool: 工具
    wheel: 备胎
    headrest: 头枕
    telephone: 电话
    extinguisher: 灭火器
    engineOil: 发动机油油位/泄露
    coolant: 防冻液液位/渗漏
    brakeFluid: 刹车油油位/渗漏
    powerSteering: 转向助力泵油油位/泄露
    windscreenWasherFluid: 玻璃清洗液液位/泄露
    polyVBelt: 皮带
    vehicleOnOutside: 车辆外部状况
    windshield: 挡风玻璃状况
    wiperBlades: 雨刮胶条状况
    tires: 轮胎状况
    brakeSystem: 刹车系统(刹车盘片厚度、漏油)
    powertrainDrivetrain: 发动机/变速箱(漏油、支脚)
    exhaustSystem: 排气系统(状况、吊耳、垫片)
    fuelSystem: 燃油系统(状况、泄露)
    rubberSealsJoints: 橡胶及球头状况
    horn: 喇叭
    windscreenWiperWasher: 雨刮器与清洗系统状况
    audioEntertainment: 音响/娱乐系统
    lighter: 点烟器
    mirror: 内/外后视镜
    windowSunRoof: 电动车窗/天窗
    seatsAndBelts: 座椅调节和安全带
    lightsInstruments: 灯光和仪表系统

serviceContractBaseData:
  silver:
    shortName: 尚银
    coverages:
      1yr: 1年
      2yr: 2年
    description: 针对车龄三年以内的车辆, 提供延长保修服务
  blue:
    shortName: 逸蓝
    coverages:
      1A1B_PLUS: 基础机油 1A1B+
      2A2B_PLUS: 基础机油 2A2B+
      3A3B_PLUS: 基础机油 3A3B+
      1A1B_AMG_PLUS: 升级机油 1A1B+
      2A2B_AMG_PLUS: 升级机油 2A2B+
      3A3B_AMG_PLUS: 升级机油 3A3B+
    description: 针对车龄三年以内的车辆, 提供常规保养中的基础A保养，基础B保养、火花塞及空调滤清器更换
  lightBlue:
    shortName: 逸蓝轻享
    coverages:
      1A1B: 基础机油 1A1B
      2A2B: 基础机油 2A2B
      3A3B: 基础机油 3A3B
      1A1B_AMG: 升级机油 1A1B
      2A2B_AMG: 升级机油 2A2B
      3A3B_AMG: 升级机油 3A3B
    description: 针对车龄届满三年的车辆，提供常规保养中的基础A和基础B保养服务