spring:
  datasource:
    url: jdbc:mysql://localhost:3309/test
    username: root
    password: dev
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.hbm2ddl.auto: update
  redis:
    host: localhost
    port: 6379
    password:
server:
  port: 18080
